// src/lib/components/ui/Particles.svelte
<script lang="ts">
    import { onMount } from "svelte";

    export let className: string = "";
    export let quantity: number = 100;
    export let staticity: number = 50;
    export let ease: number = 50;
    export let size: number = 0.4;
    export let refresh: boolean = true;
    export let color: string = "#ffffff"; // This is where you can change the base color. Use hex format.
    export let vx: number = 0;
    export let vy: number = 0;

    let canvasRef: HTMLCanvasElement;
    let canvasContainerRef: HTMLDivElement;
    let context: CanvasRenderingContext2D | null = null;
    let circles: any[] = [];
    let mouse = { x: 0, y: 0 };
    let canvasSize = { w: 0, h: 0 };
    const dpr = typeof window !== "undefined" ? window.devicePixelRatio : 1;

    function hexToRgb(hex: string): number[] {
        hex = hex.replace("#", "");

        if (hex.length === 3) {
            hex = hex
                .split("")
                .map((char) => char + char)
                .join("");
        }

        const hexInt = parseInt(hex, 16);
        const red = (hexInt >> 16) & 255;
        const green = (hexInt >> 8) & 255;
        const blue = hexInt & 255;
        return [red, green, blue];
    }

    // Convert the provided color prop to RGB
    const rgb = hexToRgb(color);

    function circleParams() {
        const x = Math.floor(Math.random() * canvasSize.w);
        const y = Math.floor(Math.random() * canvasSize.h);
        const translateX = 0;
        const translateY = 0;
        const pSize = Math.floor(Math.random() * 2) + size;
        const alpha = 0;
        // This targetAlpha determines the maximum transparency of a circle (0.2 to 1)
        // Increase the lower bound (0.2) to make circles less transparent overall.
        const targetAlpha = parseFloat((Math.random() * 0.8 + 0.8).toFixed(1));
        const dx = (Math.random() - 0.5) * 0.1;
        const dy = (Math.random() - 0.5) * 0.1;
        const magnetism = 0.1 + Math.random() * 4;
        return {
            x,
            y,
            translateX,
            translateY,
            size: pSize,
            alpha,
            targetAlpha,
            dx,
            dy,
            magnetism,
        };
    }

    function resizeCanvas() {
        if (canvasContainerRef && canvasRef && context) {
            circles.length = 0;
            canvasSize.w = canvasContainerRef.offsetWidth;
            canvasSize.h = canvasContainerRef.offsetHeight;
            canvasRef.width = canvasSize.w * dpr;
            canvasRef.height = canvasSize.h * dpr;
            canvasRef.style.width = `${canvasSize.w}px`;
            canvasRef.style.height = `${canvasSize.h}px`;
            context.scale(dpr, dpr);
        }
    }

    function clearContext() {
        if (context) {
            context.clearRect(0, 0, canvasSize.w, canvasSize.h);
        }
    }

    function drawCircle(circle, update = false) {
        if (context) {
            const { x, y, translateX, translateY, size, alpha } = circle;
            context.translate(translateX, translateY);
            context.beginPath();
            context.arc(x, y, size, 0, 2 * Math.PI);
            // This line sets the color and transparency for drawing.
            // The `alpha` variable is calculated based on distance from edge and targetAlpha.
            context.fillStyle = `rgba(${rgb.join(", ")}, ${alpha})`;
            context.fill();
            context.setTransform(dpr, 0, 0, dpr, 0, 0);

            if (!update) {
                circles.push(circle);
            }
        }
    }

    function drawParticles() {
        clearContext();
        for (let i = 0; i < quantity; i++) {
            const circle = circleParams();
            drawCircle(circle);
        }
    }

    function remapValue(value, start1, end1, start2, end2) {
        let remapped =
            ((value - start1) * (end2 - start2)) / (end1 - start1) + start2;
        return remapped > 0 ? remapped : 0;
    }

    function animate() {
        clearContext();
        circles.forEach((circle, i) => {
            const edge = [
                circle.x + circle.translateX - circle.size,
                canvasSize.w - circle.x - circle.translateX - circle.size,
                circle.y + circle.translateY - circle.size,
                canvasSize.h - circle.y - circle.translateY - circle.size,
            ];
            const closestEdge = edge.reduce((a, b) => Math.min(a, b));
            const remapClosestEdge = parseFloat(
                remapValue(closestEdge, 0, 20, 0, 1).toFixed(2),
            );
            if (remapClosestEdge > 1) {
                circle.alpha += 0.02;
                if (circle.alpha > circle.targetAlpha) {
                    circle.alpha = circle.targetAlpha;
                }
            } else {
                // This line adjusts the alpha based on distance to the edge
                // To make them generally brighter closer to the edge, you could potentially adjust the '20' value in remapValue or the remap range.
                circle.alpha = circle.targetAlpha * remapClosestEdge;
            }
            circle.x += circle.dx + vx;
            circle.y += circle.dy + vy;
            circle.translateX +=
                (mouse.x / (staticity / circle.magnetism) - circle.translateX) /
                ease;
            circle.translateY +=
                (mouse.y / (staticity / circle.magnetism) - circle.translateY) /
                ease;

            drawCircle(circle, true);

            if (
                circle.x < -circle.size ||
                circle.x > canvasSize.w + circle.size ||
                circle.y < -circle.size ||
                circle.y > canvasSize.h + circle.size
            ) {
                circles.splice(i, 1);
                const newCircle = circleParams();
                drawCircle(newCircle);
            }
        });
        window.requestAnimationFrame(animate);
    }

    function onMouseMove(event: MouseEvent) {
        if (canvasRef) {
            let rect = canvasRef.getBoundingClientRect();
            let { w, h } = canvasSize;
            let x = event.clientX - rect.left - w / 2;
            let y = event.clientY - rect.top - h / 2;
            let inside = x < w / 2 && x > -w / 2 && y < h / 2 && y > -h / 2;
            if (inside) {
                mouse.x = x;
                mouse.y = y;
            }
        }
    }

    onMount(() => {
        if (canvasRef) {
            context = canvasRef.getContext("2d");
            resizeCanvas();
            animate();
            window.addEventListener("resize", resizeCanvas);
            window.addEventListener("mousemove", onMouseMove);
        }

        return () => {
            window.removeEventListener("resize", resizeCanvas);
            window.removeEventListener("mousemove", onMouseMove);
        };
    });

    $: {
        if (canvasRef) {
            drawParticles();
            //   animate();
        }
    }
    //   Building Stage
</script>

<div class={className} bind:this={canvasContainerRef} aria-hidden="true">
    <canvas bind:this={canvasRef} class="size-full"></canvas>
</div>

<style>
    .size-full {
        width: 100%;
        height: 100%;
    }
</style>

// src/components/magicui/particles.tsx
"use client";

import React, { useEffect, useRef, useState } from "react";

interface MousePosition {
  x: number;
  y: number;
}

function useMousePosition(): MousePosition {
  const [mousePosition, setMousePosition] = useState<MousePosition>({
    x: 0,
    y: 0,
  });

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      setMousePosition({ x: event.clientX, y: event.clientY });
    };

    window.addEventListener("mousemove", handleMouseMove);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  return mousePosition;
}

interface ParticlesProps {
  className?: string;
  quantity?: number;
  staticity?: number;
  ease?: number;
  size?: number;
  refresh?: boolean;
  color?: string;
  vx?: number;
  vy?: number;
}

const Particles: React.FC<ParticlesProps> = ({
  className = "",
  quantity = 100,
  staticity = 50,
  ease = 50,
  size = 0.4,
  refresh = false,
  color = "#ffffff",
  vx = 0,
  vy = 0,
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const canvasContainerRef = useRef<HTMLDivElement>(null);
  const context = useRef<CanvasRenderingContext2D | null>(null);
  const circles = useRef<any[]>([]);
  const mousePosition = useMousePosition();
  const mouse = useRef<{ x: number; y: number }>({ x: 0, y: 0 });
  const canvasSize = useRef<{ w: number; h: number }>({ w: 0, h: 0 });
  const dpr = typeof window !== "undefined" ? window.devicePixelRatio : 1;

  useEffect(() => {
    if (canvasRef.current) {
      context.current = canvasRef.current.getContext("2d");
    }
    initCanvas();
    animate();
    window.addEventListener("resize", initCanvas);

    return () => {
      window.removeEventListener("resize", initCanvas);
    };
  }, [color]);

  useEffect(() => {
    onMouseMove();
  }, [mousePosition.x, mousePosition.y]);

  useEffect(() => {
    initCanvas();
  }, [refresh]);

  const initCanvas = () => {
    resizeCanvas();
    drawParticles();
  };

  const onMouseMove = () => {
    if (canvasRef.current) {
      const rect = canvasRef.current.getBoundingClientRect();
      const { w, h } = canvasSize.current;
      const x = mousePosition.x - rect.left;
      const y = mousePosition.y - rect.top;
      const inside = x < w && x > 0 && y < h && y > 0;
      if (inside) {
        mouse.current.x = x;
        mouse.current.y = y;
      }
    }
  };

  type Circle = {
    x: number;
    y: number;
    translateX: number;
    translateY: number;
    size: number;
    alpha: number;
    targetAlpha: number;
    dx: number;
    dy: number;
    magnetism: number;
  };

  const resizeCanvas = () => {
    if (canvasContainerRef.current && canvasRef.current && context.current) {
      circles.current = [];
      canvasSize.current.w = canvasContainerRef.current.offsetWidth;
      canvasSize.current.h = canvasContainerRef.current.offsetHeight;
      canvasRef.current.width = canvasSize.current.w * dpr;
      canvasRef.current.height = canvasSize.current.h * dpr;
      canvasRef.current.style.width = `${canvasSize.current.w}px`;
      canvasRef.current.style.height = `${canvasSize.current.h}px`;
      context.current.scale(dpr, dpr);
    }
  };

  const circleParams = (): Circle => {
    const x = Math.floor(Math.random() * canvasSize.current.w);
    const y = Math.floor(Math.random() * canvasSize.current.h);
    const translateX = 0;
    const translateY = 0;
    const pSize = Math.floor(Math.random() * 2) + size;
    const alpha = 0;
    const targetAlpha = parseFloat((Math.random() * 0.6 + 0.1).toFixed(1));
    const dx = (Math.random() - 0.5) * 0.1 + vx;
    const dy = (Math.random() - 0.5) * 0.1 + vy;
    const magnetism = 0.1 + Math.random() * 4;
    return {
      x,
      y,
      translateX,
      translateY,
      size: pSize,
      alpha,
      targetAlpha,
      dx,
      dy,
      magnetism,
    };
  };

  const drawCircle = (circle: Circle, update = false) => {
    if (context.current) {
      const { x, y, translateX, translateY, size, alpha } = circle;
      context.current.translate(translateX, translateY);
      context.current.beginPath();
      context.current.arc(x, y, size, 0, 2 * Math.PI);
      context.current.fillStyle = hexToRgb(color, alpha);
      context.current.fill();
      context.current.setTransform(dpr, 0, 0, dpr, 0, 0);

      if (!update) {
        circles.current.push(circle);
      }
    }
  };

  const hexToRgb = (hex: string, alpha: number): string => {
    hex = hex.replace("#", "");
    const r = parseInt(hex.substring(0, 2), 16);
    const g = parseInt(hex.substring(2, 4), 16);
    const b = parseInt(hex.substring(4, 6), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  };

  const drawParticles = () => {
    for (let i = 0; i < quantity; i++) {
      const circle = circleParams();
      drawCircle(circle);
    }
  };

  const remapValue = (
    value: number,
    start1: number,
    end1: number,
    start2: number,
    end2: number,
  ): number => {
    const remapped =
      ((value - start1) * (end2 - start2)) / (end1 - start1) + start2;
    return remapped > 0 ? remapped : 0;
  };

  const animate = () => {
    clearContext();
    circles.current.forEach((circle: Circle, i: number) => {
      // Handle the alpha animation
      const edge = [
        circle.x + circle.translateX - circle.size, // left
        canvasSize.current.w - circle.x - circle.translateX - circle.size, // right
        circle.y + circle.translateY - circle.size, // top
        canvasSize.current.h - circle.y - circle.translateY - circle.size, // bottom
      ];
      const closestEdge = edge.reduce((a, b) => Math.min(a, b));
      const remapClosestEdge = parseFloat(
        remapValue(closestEdge, 0, 20, 0, 1).toFixed(2),
      );
      if (remapClosestEdge > 1) {
        circle.alpha += 0.02;
        if (circle.alpha > circle.targetAlpha) {
          circle.alpha = circle.targetAlpha;
        }
      } else {
        circle.alpha = circle.targetAlpha * remapClosestEdge;
      }

      circle.x += circle.dx;
      circle.y += circle.dy;
      circle.translateX +=
        (mouse.current.x / (staticity / circle.magnetism) - circle.translateX) /
        ease;
      circle.translateY +=
        (mouse.current.y / (staticity / circle.magnetism) - circle.translateY) /
        ease;

      // circle within bounds
      if (
        circle.x < -circle.size ||
        circle.x > canvasSize.current.w + circle.size ||
        circle.y < -circle.size ||
        circle.y > canvasSize.current.h + circle.size
      ) {
        // remove the circle from the array
        circles.current.splice(i, 1);
        // add a new circle
        const newCircle = circleParams();
        drawCircle(newCircle);
        // update the alpha to 0
        newCircle.alpha = 0;
      } else {
        drawCircle(
          {
            ...circle,
            x: circle.x,
            y: circle.y,
            translateX: circle.translateX,
            translateY: circle.translateY,
            alpha: circle.alpha,
          },
          true,
        );
      }
    });
    window.requestAnimationFrame(animate);
  };

  const clearContext = () => {
    if (context.current) {
      context.current.clearRect(
        0,
        0,
        canvasSize.current.w,
        canvasSize.current.h,
      );
    }
  };

  return (
    <div
      className={className}
      ref={canvasContainerRef}
      aria-hidden="true"
    >
      <canvas ref={canvasRef} />
    </div>
  );
};

export default Particles;
